name: Node Continuous Integration

# which events should trigger this workflow
on:
  # trigger workflow on push to main branch
  push:
    branches: [main]

# jobs to run
jobs:
  # job name
  test_push_request:
    # job runs on ubuntu
    runs-on: ubuntu-latest
    # steps to run
    steps:
      # bring source code into repository into the container to run tests on it
      - uses: actions/checkout@main
      # install node
      - uses: actions/setup-node@main
        with:
          node-version: 19
      # install dependencies (like yarn install)
      - run: yarn install
      - run: yarn run test
      # - run: yarn run test

      # automatically delete the branch after the workflow runs
      retention-days: 7
