name: Node Continuous Integration

# which events should trigger this workflow
on:
  # trigger workflow on push to main branch
  push:
    branches: [main]
  # trigger workflow on pull request to main branch
  pull_request:
    branches: [main]

# jobs to run
jobs:
  # job name
  test_pull_request:
    # job runs on ubuntu
    runs-on: ubuntu-latest
    # steps to run
    steps:
      # bring source code into the current working directory to run tests on it
      - uses: actions/checkout@v2
      # install node
      - uses: actions/setup-node@v1
        with:
          node-version: 19
      # install dependencies (like yarn install)
      - run: yarn install
      - run: yarn run test
      - run: yarn run dev
